// rand_seed_gen.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

extern unsigned int tab_ui[];
extern unsigned int tab_ui_size;

extern unsigned char tab_uc[];
extern unsigned int tab_uc_size;


int _tmain(int argc, _TCHAR* argv[])
{
	//srand(time(NULL));

	unsigned int probes = tab_uc_size / sizeof(unsigned char);

	int cnt = 128;

	FILE* f = fopen("rand_seed.c", "wb");


	fprintf(f, "// generated by rand_seed_gen" __DATE__ "; " __TIME__ " \n");
	fprintf(f, "//\n");
	fprintf(f, "\n");
	fprintf(f, "unsigned char __rand_seed[%d] = {\n", cnt);
	int c = 0;
	bool nl = false;
	int counter = cnt;
	while(counter-- > 0)
	{
		unsigned int q;
		rand_s(&q);
		q = q % probes;

		fprintf(f, "0x%02X, ", tab_uc[q]);
		nl = false;
		Sleep(0);
		if (c++ == 10)
		{
			fprintf(f, "\n");
			c = 0;
			nl = true;
		}
	}

	if (!nl)
		fprintf(f, "\n");
	fprintf(f, "};\n");
	fclose(f);

	f = fopen("rand_seed.h", "wb");
	fprintf(f, "#if !defined(__RAND_SEED_H_)\n");
	fprintf(f, "#define _RAND_SEED_H_\n");
	fprintf(f, "\n");
	fprintf(f, "extern unsigned char __rand_seed[%d];\n", cnt);
	fprintf(f, "\n");
	fprintf(f, "#endif\n");
	fprintf(f, "\n");
	fclose(f);

}

